services:
    jiotv_go:
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
          - JIOTV_EPG=${JIOTV_EPG}
          - JIOTV_DEBUG=${JIOTV_DEBUG}
          - JIOTV_DISABLE_TS_HANDLER=${JIOTV_DISABLE_TS_HANDLER}
          - JIOTV_DRM=${JIOTV_DRM}
        ports:
            - ${PORT_1}:5001
        volumes:
            - ~/docker/jiotv_go/:/app/.jiotv_go
            - ~/docker/jiotv_go/secrets:/app/secrets
        image: ghcr.io/jiotv-go/jiotv_go