global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'localhost:9100' # Node Exporter on the central server itself
        - '100.71.235.1:9100' # Monitored Server 2 in-oc-1
        - '100.124.17.27:9100' # Monitored Server 3 in-pi-bkp
        - '100.103.209.86:9100' # Monitored Server 4 sg-pi-home